apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbourline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rkhnania/harbourline-k8s-lab.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: harbourline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
