apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbourline-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rkhnania/harbourline-k8s-lab.git
    targetRevision: main
    path: helm/harbourline
    helm:
      releaseName: web
      valueFiles:
        - values.yaml
        - values-web.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbourline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
