name: harbourline-web
containerName: web
replicaCount: 2

image:
  repository: ghcr.io/rkhnania/harbourline-web
  tag: "fef7d88"

podSecurityContext:
  runAsUser: 101

envFrom: null

volumes:
  - name: tmp
    emptyDir: {}
  - name: cache
    emptyDir: {}

volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: cache
    mountPath: /var/cache/nginx

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: null
    memory: 128Mi

readinessProbe:
  httpGet:
    path: /
    port: 8080
  periodSeconds: 5
  initialDelaySeconds: 0

livenessProbe:
  httpGet:
    path: /
    port: 8080
  periodSeconds: 10
  initialDelaySeconds: 0

service:
  port: 80
  targetPort: 8080
