apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbourline

resources:
- configmap.yaml
- db-statefulset.yaml
- db-init-job.yaml
- ingress.yaml

images:

labels:
- pairs:
    app.kubernetes.io/part-of: harbourline
