apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbourline

resources:
- configmap.yaml
- db-deployment.yaml
- db-init-job.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- reports-deployment.yaml
- reports-service.yaml
- ingress.yaml

images:
- name: harbourline/api
  newName: ghcr.io/rkhnania/harbourline-api
  newTag: e2ad9ea
- name: harbourline/reports
  newName: ghcr.io/rkhnania/harbourline-reports
  newTag: e2ad9ea
- name: harbourline/web
  newName: ghcr.io/rkhnania/harbourline-web
  newTag: e2ad9ea

labels:
- pairs:
    app.kubernetes.io/part-of: harbourline
